# version: '3.8'

services:
  # Servicio para la base de datos PostgreSQL
  db:
    image: postgres:13
    container_name: postgres_container
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  # Servicio para tu aplicación
  app:
    build: .
    container_name: app_container
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8833:8833"
    networks:
      - app_network

  # Servicio para pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: julioczapatao@abc.com  # Cambia esto por tu correo
      PGADMIN_DEFAULT_PASSWORD: 12345  # Cambia esto por tu contraseña
    ports:
      - "8080:80"  # Puedes cambiar el puerto si lo deseas
    depends_on:
      - db
    networks:
      - app_network

# Definimos una red compartida
networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
